openapi: 3.0.0
info:
  title: Spice Junction
  version: 1.0.0
servers:
  - url: https://spice-junction.onrender.com
components:
  securitySchemes:
    noauthAuth:
      type: http
      scheme: noauth
tags:
  - name: Authentication/User
  - name: Restaurant
  - name: Food Menu
  - name: Food Item
  - name: Category
  - name: Sub Category
  - name: Order
  - name: Delivery Zone
  - name: Admin
  - name: Restaurant Panel
  - name: Search/Sort
  - name: Payment
  - name: Blogs
paths:
  /signup:
    post:
      tags:
        - Authentication/User
      summary: signup
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                firstName: John
                lastName: Doe
                email: roroh70043@ishense.com
                password: Spicejtn@12
                phone: '9845768333'
      security:
        - noauthAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /admin/signup:
    post:
      tags:
        - Authentication/User
      summary: admin/signup
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                firstName: Franklyn
                lastName: Gomes
                email: franklyngomes15@gmail.com
                password: Admin_12345
                phone: '9845768333'
      security:
        - noauthAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /signin:
    post:
      tags:
        - Authentication/User
      summary: signin
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: quadeyaunifre-8075@yopmail.com
                password: Customer_1234
      security:
        - noauthAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /forgot-password:
    post:
      tags:
        - Authentication/User
      summary: forgot-password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: quadeyaunifre-8075@yopmail.com
      security:
        - noauthAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /reset-password:
    post:
      tags:
        - Authentication/User
      summary: reset-password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: quadeyaunifre-8075@yopmail.com
                code: '416384'
                newPassword: Customer_1234
      security:
        - noauthAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /user-profile/{id}:
    get:
      tags:
        - Authentication/User
      summary: user-profile
      security:
        - noauthAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 68bea9b51a3871015b45f6cb
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /restaurant/signup:
    post:
      tags:
        - Authentication/User
      summary: restaurant/signup
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                firstName: Jason
                lastName: Duval
                email: g3dyc@powerscrews.com
                password: Res_12345
                phone: '9845768333'
      security:
        - noauthAuth: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /set-user-address/{id}:
    post:
      tags:
        - Authentication/User
      summary: set-user-address
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                buildingNo: 35,
                street: Ballygunge Circular Rd, Ballygunge
                city: Kolkata
                pinCode: '700019'
      security:
        - noauthAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 68bea9b51a3871015b45f6cb
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /delete-user-address/{id}:
    delete:
      tags:
        - Authentication/User
      summary: delete-user-address
      security:
        - noauthAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 68c9010b23e3b1f2bda8c54c
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /all-restaurant:
    get:
      tags:
        - Restaurant
      summary: all-restaurant
      security:
        - noauthAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /restaurant-details/{id}:
    get:
      tags:
        - Restaurant
      summary: restaurant-details
      security:
        - noauthAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 68c2d209bb5dcc00c93e7927
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /update-restaurant/{id}:
    patch:
      tags:
        - Restaurant
      summary: update-restaurant
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Vertex - Fairfield by Marriott
                ownerId:
                  type: string
                  example: 68c1638b62ba343428ccc74e
                buildingNo:
                  type: string
                  example: Cb 218
                street:
                  type: string
                  example: Action Area 1C New Town Near State Bank Of India
                city:
                  type: string
                  example: Kolkata
                pinCode:
                  type: integer
                  example: '700156'
                phone:
                  type: integer
                  example: '7605086818'
                cuisine:
                  type: string
                  example: Finger Food
                deliveryZone:
                  type: string
                  example: 68c111460db754e3111cd548
                image:
                  type: string
                  format: binary
      security:
        - noauthAuth: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: number
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGMyZDFhMWJiNWRjYzAwYzkzZTc5MjAiLCJmaXJzdE5hbWUiOiJKb2huIiwibGFzdE5hbWUiOiJEb2UiLCJlbWFpbCI6IjNqdHZ1QHBvd2Vyc2NyZXdzLmNvbSIsInJvbGUiOiJyZXN0YXVyYW50IiwiaWF0IjoxNzU4Njg0OTQ1LCJleHAiOjE3NTg5NDQxNDV9.43zPfn_DmIH1A3v3Vru3kqM_-znuih5ffeL_U7M4Mj4
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 68d41aa3bcf295eb52f5b6b3
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /restaurant-by-owner/{id}:
    get:
      tags:
        - Restaurant
      summary: restaurant-by-owner
      security:
        - noauthAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 68c2d1a1bb5dcc00c93e7920
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /create-food-menu:
    post:
      tags:
        - Food Menu
      summary: create-food-menu
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Biryani
                restaurant: 68d68e9efa1f1818435b9d57
      security:
        - noauthAuth: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGMyZDFhMWJiNWRjYzAwYzkzZTc5MjAiLCJmaXJzdE5hbWUiOiJKb2huIiwibGFzdE5hbWUiOiJEb2UiLCJlbWFpbCI6IjNqdHZ1QHBvd2Vyc2NyZXdzLmNvbSIsInJvbGUiOiJyZXN0YXVyYW50IiwiaWF0IjoxNzU4ODY4MTQ0LCJleHAiOjE3NTkxMjczNDR9.nqGJnX3nLLbx9iUQ6Yv2EMuAy8dXAkhe-rLQjj0VQFU
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /all-food-menu:
    get:
      tags:
        - Food Menu
      summary: all-food-menu
      security:
        - noauthAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /food-menu-details/{id}:
    get:
      tags:
        - Food Menu
      summary: food-menu-details
      security:
        - noauthAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 68c3c39d5cdde5fd45a87c87
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /delete-food-menu/{id}:
    delete:
      tags:
        - Food Menu
      summary: delete-food-menu
      security:
        - noauthAuth: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: number
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGMyZDFhMWJiNWRjYzAwYzkzZTc5MjAiLCJmaXJzdE5hbWUiOiJKb2huIiwibGFzdE5hbWUiOiJEb2UiLCJlbWFpbCI6IjNqdHZ1QHBvd2Vyc2NyZXdzLmNvbSIsInJvbGUiOiJyZXN0YXVyYW50IiwiaWF0IjoxNzU3NjYwMDQ4LCJleHAiOjE3NTc2NzA4NDh9.6r3VkkEMI-7zUR7fdCt2OFSt_Bi8CKSCmteeRbksxi8
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 68c3c4fc5cdde5fd45a87c90
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /update-food-menu/{id}:
    patch:
      tags:
        - Food Menu
      summary: update-food-menu
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Chicken Main Course
      security:
        - noauthAuth: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: number
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGMyZDFhMWJiNWRjYzAwYzkzZTc5MjAiLCJmaXJzdE5hbWUiOiJKb2huIiwibGFzdE5hbWUiOiJEb2UiLCJlbWFpbCI6IjNqdHZ1QHBvd2Vyc2NyZXdzLmNvbSIsInJvbGUiOiJyZXN0YXVyYW50IiwiaWF0IjoxNzU3NjYwMDQ4LCJleHAiOjE3NTc2NzA4NDh9.6r3VkkEMI-7zUR7fdCt2OFSt_Bi8CKSCmteeRbksxi8
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 68c3c4fc5cdde5fd45a87c90
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /restaurant-food-menu/{restaurantid}:
    get:
      tags:
        - Food Menu
      summary: restaurant-food-menu
      security:
        - noauthAuth: []
      parameters:
        - name: restaurantid
          in: path
          schema:
            type: string
          required: true
          example: 68d68e9efa1f1818435b9d57
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /restaurant-food-item/{restaurantid}:
    get:
      tags:
        - Food Item
      summary: restaurant-food-item
      security:
        - noauthAuth: []
      parameters:
        - name: restaurantid
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /create-food-item:
    post:
      tags:
        - Food Item
      summary: create-food-item
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Chowman's Favourite Soup
                description:
                  type: string
                  example: >-
                    From the house of Chowman, our very own specialty soup is a
                    pure bliss that comes with an amalgamation of two different
                    soups in perfect proportion, adding up luxury ingredients
                    such as prawn, Pak Choi, egg drops, mushrooms, boneless
                    chicken and many more
                restaurant:
                  type: string
                  example: 68d68e9efa1f1818435b9d57
                subCategory:
                  type: string
                  example: 68d8f929256e1772e897eee8
                price:
                  type: integer
                  example: '315'
                menu:
                  type: string
                  example: 68d8a249071ca717c0fc8693
                image:
                  type: string
                  format: binary
      security:
        - noauthAuth: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGMyZDFhMWJiNWRjYzAwYzkzZTc5MjAiLCJmaXJzdE5hbWUiOiJKb2huIiwibGFzdE5hbWUiOiJEb2UiLCJlbWFpbCI6IjNqdHZ1QHBvd2Vyc2NyZXdzLmNvbSIsInJvbGUiOiJyZXN0YXVyYW50IiwiaWF0IjoxNzU4ODY4MTQ0LCJleHAiOjE3NTkxMjczNDR9.nqGJnX3nLLbx9iUQ6Yv2EMuAy8dXAkhe-rLQjj0VQFU
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /food-item-details/{id}:
    get:
      tags:
        - Food Item
      summary: food-item-details
      security:
        - noauthAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 68d8bb437fe414211986314f
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /update-food-item/{id}:
    patch:
      tags:
        - Food Item
      summary: update-food-item
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Test Data 123345345
                description:
                  type: string
                  example: >-
                    Marinated chicken with sauteed garlic tossed in butter and
                    sweet ketchup
                restaurant:
                  type: string
                  example: 68c2d209bb5dcc00c93e7927
                subCategory:
                  type: string
                  example: 68c256de19895d64ea0cf241
                price:
                  type: integer
                  example: '350'
                menu:
                  type: string
                  example: 68c44fb69e3b35a99c29a782
                image:
                  type: string
                  format: binary
      security:
        - noauthAuth: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: number
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGMyZDFhMWJiNWRjYzAwYzkzZTc5MjAiLCJmaXJzdE5hbWUiOiJKb2huIiwibGFzdE5hbWUiOiJEb2UiLCJlbWFpbCI6IjNqdHZ1QHBvd2Vyc2NyZXdzLmNvbSIsInJvbGUiOiJyZXN0YXVyYW50IiwiaWF0IjoxNzU4Njg0OTQ1LCJleHAiOjE3NTg5NDQxNDV9.43zPfn_DmIH1A3v3Vru3kqM_-znuih5ffeL_U7M4Mj4
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 68d8bb437fe414211986314f
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /delete-food-item/{id}:
    delete:
      tags:
        - Food Item
      summary: delete-food-item
      security:
        - noauthAuth: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: number
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGMyZDFhMWJiNWRjYzAwYzkzZTc5MjAiLCJmaXJzdE5hbWUiOiJKb2huIiwibGFzdE5hbWUiOiJEb2UiLCJlbWFpbCI6IjNqdHZ1QHBvd2Vyc2NyZXdzLmNvbSIsInJvbGUiOiJyZXN0YXVyYW50IiwiaWF0IjoxNzU4Njg0OTQ1LCJleHAiOjE3NTg5NDQxNDV9.43zPfn_DmIH1A3v3Vru3kqM_-znuih5ffeL_U7M4Mj4
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 68d8bb437fe414211986314f
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /all-food-item:
    get:
      tags:
        - Food Item
      summary: all-food-item
      security:
        - noauthAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /create-category:
    post:
      tags:
        - Category
      summary: create-category
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Sweets
      security:
        - noauthAuth: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGMxNjI5ZjgyNTEwOTk3YzEwODg1OGYiLCJmaXJzdE5hbWUiOiJGcmFua2x5biIsImxhc3ROYW1lIjoiR29tZXMiLCJlbWFpbCI6ImZyYW5rbHluZ29tZXMxNUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTg0MzkwMDgsImV4cCI6MTc1ODY5ODIwOH0.VVpiHWtfXQXAMxAJg05lAPgs3djcoeR9_5q3HuU15cc
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /all-category:
    get:
      tags:
        - Category
      summary: all-category
      security:
        - noauthAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /category-details/{id}:
    get:
      tags:
        - Category
      summary: category-details
      security:
        - noauthAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 68c1674f68f13ab404ff2484
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /category-update/{id}:
    patch:
      tags:
        - Category
      summary: category-update
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Hot Breakfast
      security:
        - noauthAuth: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGMxNjI5ZjgyNTEwOTk3YzEwODg1OGYiLCJmaXJzdE5hbWUiOiJGcmFua2x5biIsImxhc3ROYW1lIjoiR29tZXMiLCJlbWFpbCI6ImZyYW5rbHluZ29tZXMxNUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTc1MDQ5MTEsImV4cCI6MTc1NzUxNTcxMX0.uSMsgBlR0IMHIyssENrnYXbUUnE3gQ36OZEOP2J7OJc
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 68c1674f68f13ab404ff2484
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /category-delete/{id}:
    delete:
      tags:
        - Category
      summary: category-delete
      security:
        - noauthAuth: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGMxNjI5ZjgyNTEwOTk3YzEwODg1OGYiLCJmaXJzdE5hbWUiOiJGcmFua2x5biIsImxhc3ROYW1lIjoiR29tZXMiLCJlbWFpbCI6ImZyYW5rbHluZ29tZXMxNUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTc1MDQ5MTEsImV4cCI6MTc1NzUxNTcxMX0.uSMsgBlR0IMHIyssENrnYXbUUnE3gQ36OZEOP2J7OJc
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 68c1670d1e07948832b01771
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /create-sub-category:
    post:
      tags:
        - Sub Category
      summary: create-sub-category
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Ice Cream
                image:
                  type: string
                  format: binary
                category:
                  type: string
                  example: 68c1675b68f13ab404ff248a
      security:
        - noauthAuth: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: number
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGMyZDFhMWJiNWRjYzAwYzkzZTc5MjAiLCJmaXJzdE5hbWUiOiJKb2huIiwibGFzdE5hbWUiOiJEb2UiLCJlbWFpbCI6IjNqdHZ1QHBvd2Vyc2NyZXdzLmNvbSIsInJvbGUiOiJyZXN0YXVyYW50IiwiaWF0IjoxNzU4Njg0OTQ1LCJleHAiOjE3NTg5NDQxNDV9.43zPfn_DmIH1A3v3Vru3kqM_-znuih5ffeL_U7M4Mj4
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /all-sub-category:
    get:
      tags:
        - Sub Category
      summary: all-sub-category
      security:
        - noauthAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /sub-category-details/{id}:
    get:
      tags:
        - Sub Category
      summary: sub-category-details
      security:
        - noauthAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 68c2573417904b6e042a6ad8
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /update-sub-category/{id}:
    patch:
      tags:
        - Sub Category
      summary: update-sub-category
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Dhokla
                category:
                  type: string
                  example: 68c1675b68f13ab404ff248a
                image:
                  type: string
                  format: binary
      security:
        - noauthAuth: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: number
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGMyZDFhMWJiNWRjYzAwYzkzZTc5MjAiLCJmaXJzdE5hbWUiOiJKb2huIiwibGFzdE5hbWUiOiJEb2UiLCJlbWFpbCI6IjNqdHZ1QHBvd2Vyc2NyZXdzLmNvbSIsInJvbGUiOiJyZXN0YXVyYW50IiwiaWF0IjoxNzU4Njg0OTQ1LCJleHAiOjE3NTg5NDQxNDV9.43zPfn_DmIH1A3v3Vru3kqM_-znuih5ffeL_U7M4Mj4
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 68c2573417904b6e042a6ad8
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /delete-sub-category/{id}:
    delete:
      tags:
        - Sub Category
      summary: delete-sub-category
      security:
        - noauthAuth: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGMxNjI5ZjgyNTEwOTk3YzEwODg1OGYiLCJmaXJzdE5hbWUiOiJGcmFua2x5biIsImxhc3ROYW1lIjoiR29tZXMiLCJlbWFpbCI6ImZyYW5rbHluZ29tZXMxNUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTc1MDQ5MTEsImV4cCI6MTc1NzUxNTcxMX0.uSMsgBlR0IMHIyssENrnYXbUUnE3gQ36OZEOP2J7OJc
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 68c2573417904b6e042a6ad8
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /create-order:
    post:
      tags:
        - Order
      summary: create-order
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                customerId: 68bea9b51a3871015b45f6cb
                items:
                  - foodItem: 68d8bd747fe4142119863217
                    quantity: 1
                  - foodItem: 68da2876a008ee1d14945bbb
                    quantity: 2
                buildingNo: Haldia Petrochemical Building
                street: Sector v, Wipro More
                city: Kolkata
                pinCode: '700156'
      security:
        - noauthAuth: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGJlYTliNTFhMzg3MTAxNWI0NWY2Y2IiLCJmaXJzdE5hbWUiOiJKb2huIiwibGFzdE5hbWUiOiJEb2UiLCJlbWFpbCI6InF1YWRleWF1bmlmcmUtODA3NUB5b3BtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTc1OTMwNzczNCwiZXhwIjoxNzU5NTY2OTM0fQ.ykkZYeH2Ibmj8rcoVguyYjZGmgL8BuIcQgd2SeVR4yc
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /all-order:
    get:
      tags:
        - Order
      summary: all-order
      security:
        - noauthAuth: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGJlYTliNTFhMzg3MTAxNWI0NWY2Y2IiLCJmaXJzdE5hbWUiOiJKb2huIiwibGFzdE5hbWUiOiJEb2UiLCJlbWFpbCI6InF1YWRleWF1bmlmcmUtODA3NUB5b3BtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTc1NzkyODUyNCwiZXhwIjoxNzU3OTM5MzI0fQ.Cl6FIOueuSU9sRblmu5qad-mvUn3qCShGt0f_seOjVE
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /customer-order-history/{customerid}:
    get:
      tags:
        - Order
      summary: customer-order-history
      security:
        - noauthAuth: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGJlYTliNTFhMzg3MTAxNWI0NWY2Y2IiLCJmaXJzdE5hbWUiOiJKb2huIiwibGFzdE5hbWUiOiJEb2UiLCJlbWFpbCI6InF1YWRleWF1bmlmcmUtODA3NUB5b3BtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTc1OTc3ODQyMiwiZXhwIjoxNzYwMDM3NjIyfQ.79WKFrTHSrIIlSGSCGtHsJ5hZxbrAnNjcp8p2Pp9Cr0
        - name: customerid
          in: path
          schema:
            type: string
          required: true
          example: 68bea9b51a3871015b45f6cb
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /order-by-restaurant/{restaurantid}:
    get:
      tags:
        - Order
      summary: order-by-restaurant
      security:
        - noauthAuth: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGJlYTliNTFhMzg3MTAxNWI0NWY2Y2IiLCJmaXJzdE5hbWUiOiJKb2huIiwibGFzdE5hbWUiOiJEb2UiLCJlbWFpbCI6InF1YWRleWF1bmlmcmUtODA3NUB5b3BtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTc1NzkyODUyNCwiZXhwIjoxNzU3OTM5MzI0fQ.Cl6FIOueuSU9sRblmu5qad-mvUn3qCShGt0f_seOjVE
        - name: restaurantid
          in: path
          schema:
            type: string
          required: true
          example: 68c2d209bb5dcc00c93e7927
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /order-update/{id}:
    patch:
      tags:
        - Order
      summary: order-update
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                status: preparing
      security:
        - noauthAuth: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: number
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGMyZDVlYmM4MjVhZTc2MGQwNjMwOWMiLCJmaXJzdE5hbWUiOiJKYXNvbiIsImxhc3ROYW1lIjoiRHV2YWwiLCJlbWFpbCI6ImczZHljQHBvd2Vyc2NyZXdzLmNvbSIsInJvbGUiOiJyZXN0YXVyYW50IiwiaWF0IjoxNzU3OTI5NzI2LCJleHAiOjE3NTc5NDA1MjZ9.2aDskQ-6MWp2ljJkxiof8-ccF__iD-83qqTm8qhu-vU
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 68c7d73da5b9e1e410a30e07
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /order-delete/{id}:
    delete:
      tags:
        - Order
      summary: order-delete
      security:
        - noauthAuth: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGMxNjI5ZjgyNTEwOTk3YzEwODg1OGYiLCJmaXJzdE5hbWUiOiJGcmFua2x5biIsImxhc3ROYW1lIjoiR29tZXMiLCJlbWFpbCI6ImZyYW5rbHluZ29tZXMxNUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTc5Mjk5NTksImV4cCI6MTc1Nzk0MDc1OX0.VOLP3jzNsibIOUzo3vGUYmBreXTtfG1zp4TvOqy1gtU
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 68c7e19923ecf26b782d010e
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /order-details/{id}:
    get:
      tags:
        - Order
      summary: order-details
      security:
        - noauthAuth: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGJlYTliNTFhMzg3MTAxNWI0NWY2Y2IiLCJmaXJzdE5hbWUiOiJKb2huIiwibGFzdE5hbWUiOiJEb2UiLCJlbWFpbCI6InF1YWRleWF1bmlmcmUtODA3NUB5b3BtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTc1Nzk0ODEyNCwiZXhwIjoxNzU4MjA3MzI0fQ.yTG_b02FKSaZ-U6leKqBMoA7pBUVUsg9ydEWrVV1GZk
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 68c7d73da5b9e1e410a30e07
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /customer-pending-order/{customerid}:
    get:
      tags:
        - Order
      summary: customer-pending-order
      security:
        - noauthAuth: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGJlYTliNTFhMzg3MTAxNWI0NWY2Y2IiLCJmaXJzdE5hbWUiOiJKb2huIiwibGFzdE5hbWUiOiJEb2UiLCJlbWFpbCI6InF1YWRleWF1bmlmcmUtODA3NUB5b3BtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTc1OTc3ODQyMiwiZXhwIjoxNzYwMDM3NjIyfQ.79WKFrTHSrIIlSGSCGtHsJ5hZxbrAnNjcp8p2Pp9Cr0
        - name: customerid
          in: path
          schema:
            type: string
          required: true
          example: 68bea9b51a3871015b45f6cb
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /create-delivery-zone:
    post:
      tags:
        - Delivery Zone
      summary: create-delivery-zone
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                zoneName: Dum Dum
                district: North 24 Parganas
      security:
        - noauthAuth: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGMxNjI5ZjgyNTEwOTk3YzEwODg1OGYiLCJmaXJzdE5hbWUiOiJGcmFua2x5biIsImxhc3ROYW1lIjoiR29tZXMiLCJlbWFpbCI6ImZyYW5rbHluZ29tZXMxNUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTc1OTg2MzQsImV4cCI6MTc1NzYwOTQzNH0.XvAQc4avl4WPUcTJDu5zlfQRGVJSBFIPBir49PaBHZw
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /all-delivery-zone:
    get:
      tags:
        - Delivery Zone
      summary: all-delivery-zone
      security:
        - noauthAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /delivery-zone-details/{id}:
    get:
      tags:
        - Delivery Zone
      summary: delivery-zone-details
      security:
        - noauthAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 68c11b92a3275b7ddd0a2689
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /delete-delivery-zone/{id}:
    delete:
      tags:
        - Delivery Zone
      summary: delete-delivery-zone
      security:
        - noauthAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 68c11b92a3275b7ddd0a2689
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /admin/get-restaurant-request:
    get:
      tags:
        - Admin
      summary: admin/get-restaurant-request
      security:
        - noauthAuth: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGMxNjI5ZjgyNTEwOTk3YzEwODg1OGYiLCJmaXJzdE5hbWUiOiJGcmFua2x5biIsImxhc3ROYW1lIjoiR29tZXMiLCJlbWFpbCI6ImZyYW5rbHluZ29tZXMxNUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTg5NDA1NDAsImV4cCI6MTc1OTE5OTc0MH0.jZXhVy6_ESSoI3X5NxVG_oESF-2Hn7Egd4wKzJBddgs
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /admin/respond-restaurant-request/{id}:
    patch:
      tags:
        - Admin
      summary: respond-restaurant-request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                response: true
      security:
        - noauthAuth: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: number
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGMxNjI5ZjgyNTEwOTk3YzEwODg1OGYiLCJmaXJzdE5hbWUiOiJGcmFua2x5biIsImxhc3ROYW1lIjoiR29tZXMiLCJlbWFpbCI6ImZyYW5rbHluZ29tZXMxNUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTc2MDAzNjMsImV4cCI6MTc1NzYxMTE2M30.8mdtMpaKn6VA-5Bq3Yy7Sz6jvj_pstY4ltV0Iequ4kQ
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 68c2da329dc267c4bb6ca1c3
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /delete-restaurant/{id}:
    delete:
      tags:
        - Admin
      summary: delete-restaurant
      security:
        - noauthAuth: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGMxNjI5ZjgyNTEwOTk3YzEwODg1OGYiLCJmaXJzdE5hbWUiOiJGcmFua2x5biIsImxhc3ROYW1lIjoiR29tZXMiLCJlbWFpbCI6ImZyYW5rbHluZ29tZXMxNUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTg3MzAyMzIsImV4cCI6MTc1ODk4OTQzMn0.hSQeLUqGX1NtiWM5OGTTx6UG5mM1hQ-VnY2lmPsc0UM
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 68d41aa3bcf295eb52f5b6b3
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /create-restaurant:
    post:
      tags:
        - Restaurant Panel
      summary: create-restaurant
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Arsalaan
                ownerId:
                  type: string
                  example: 68c2d5ebc825ae760d06309c
                buildingNo:
                  type: string
                  example: 123,
                street:
                  type: string
                  example: Jessore Rd, Shyam Nagar, Satgachi, South Dumdum,
                city:
                  type: string
                  example: Kolkata
                pinCode:
                  type: integer
                  example: '700055'
                phone:
                  type: integer
                  example: '7439513775'
                cuisine:
                  type: string
                  example: Mughlai
                image:
                  type: string
                  format: binary
                deliveryZone:
                  type: string
                  example: 68c2d8f4c825ae760d0630ba
      security:
        - noauthAuth: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGMyZDFhMWJiNWRjYzAwYzkzZTc5MjAiLCJmaXJzdE5hbWUiOiJKb2huIiwibGFzdE5hbWUiOiJEb2UiLCJlbWFpbCI6IjNqdHZ1QHBvd2Vyc2NyZXdzLmNvbSIsInJvbGUiOiJyZXN0YXVyYW50IiwiaWF0IjoxNzU4ODYyMzUyLCJleHAiOjE3NTkxMjE1NTJ9.oIGGR50vw5aS9bf-92u42jIXZFd4mecDVBloe6Swgo8
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /sort-by-price:
    post:
      tags:
        - Search/Sort
      summary: sort-by-price
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                min: 0
                max: 400
      security:
        - noauthAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /search:
    post:
      tags:
        - Search/Sort
      summary: search
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                searchTerm: chilli chicken
      security:
        - noauthAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /create-payment-record:
    post:
      tags:
        - Payment
      summary: payment-record
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                order: 68bea9b51a3871015b45f6cb
                amount: 1290
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /create-blog:
    post:
      tags:
        - Blogs
      summary: create-blog
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: My New Favorite Pizza Has a Cottage Cheese Crust
                description:
                  type: string
                  example: >-
                    This cottage cheese pizza crust is ridiculous. 4
                    ingredients, 20 minutes, and actually chewy, crispy, and
                    delicious.
                author:
                  type: string
                  example: 68c1629f82510997c108858f
                image:
                  type: string
                  format: binary
      security:
        - noauthAuth: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGMxNjI5ZjgyNTEwOTk3YzEwODg1OGYiLCJmaXJzdE5hbWUiOiJGcmFua2x5biIsImxhc3ROYW1lIjoiR29tZXMiLCJlbWFpbCI6ImZyYW5rbHluZ29tZXMxNUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTg3MzAyMzIsImV4cCI6MTc1ODk4OTQzMn0.hSQeLUqGX1NtiWM5OGTTx6UG5mM1hQ-VnY2lmPsc0UM
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /all-blogs:
    get:
      tags:
        - Blogs
      summary: all-blogs
      security:
        - noauthAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /blogs-details/{id}:
    get:
      tags:
        - Blogs
      summary: blogs-details
      security:
        - noauthAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 68d4200ae4ffa1160aa56e5f
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /blog-update/{id}:
    patch:
      tags:
        - Blogs
      summary: blog-update
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: My New Favorite Pizza Has a Cottage Cheese Crust
                description:
                  type: string
                  example: >-
                    This cottage cheese pizza crust is ridiculous. 4
                    ingredients, 20 minutes, and actually chewy, crispy, and
                    delicious.
                author:
                  type: string
                  example: 68c1629f82510997c108858f
                image:
                  type: string
                  format: binary
      security:
        - noauthAuth: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGMxNjI5ZjgyNTEwOTk3YzEwODg1OGYiLCJmaXJzdE5hbWUiOiJGcmFua2x5biIsImxhc3ROYW1lIjoiR29tZXMiLCJlbWFpbCI6ImZyYW5rbHluZ29tZXMxNUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTg3MzAyMzIsImV4cCI6MTc1ODk4OTQzMn0.hSQeLUqGX1NtiWM5OGTTx6UG5mM1hQ-VnY2lmPsc0UM
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 68d41fe1e4ffa1160aa56e5b
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /blog-delete/{id}:
    delete:
      tags:
        - Blogs
      summary: blog-delete
      security:
        - noauthAuth: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGMxNjI5ZjgyNTEwOTk3YzEwODg1OGYiLCJmaXJzdE5hbWUiOiJGcmFua2x5biIsImxhc3ROYW1lIjoiR29tZXMiLCJlbWFpbCI6ImZyYW5rbHluZ29tZXMxNUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTg3MzAyMzIsImV4cCI6MTc1ODk4OTQzMn0.hSQeLUqGX1NtiWM5OGTTx6UG5mM1hQ-VnY2lmPsc0UM
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 68d41fe1e4ffa1160aa56e5b
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
